cc_binary(
    name = "helloworld",
    srcs = [
        "helloworld.cc",
    ],
    deps = [
      "@com_google_absl//absl/flags:flag",
      "@com_google_absl//absl/flags:parse",
      "@com_google_absl//absl/log",
      "@com_google_absl//absl/log:flags",      
      "@com_google_absl//absl/log:initialize",
    ]
)

